#!/usr/bin/env python3
"""Train a small dependency-free gray96 baseline for EdgeCare."""

from __future__ import annotations

import argparse
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path

import dataset_quality


FEATURE_COUNT = 20
LABEL_TO_TARGET = {
    "empty": 0,
    "safe": 0,
    "intrusion": 1,
}


@dataclass
class TrainingResult:
    total_samples: int
    train_samples: int
    val_samples: int
    export_samples: int
    val_accuracy: float
    confusion: dict[str, int]
    export_weights: list[float]
    out_dir: Path


def sigmoid(value: float) -> float:
    if value >= 0:
        z = math.exp(-value)
        return 1.0 / (1.0 + z)
    z = math.exp(value)
    return z / (1.0 + z)


def gray_features(pixels: bytes, width: int, height: int) -> list[float]:
    count = width * height
    values = [pixel / 255.0 for pixel in pixels]
    mean = sum(values) / count
    min_value = min(values)
    max_value = max(values)
    contrast = max_value - min_value

    features = [1.0, mean, min_value, max_value, contrast]
    grid = 4
    for gy in range(grid):
        y0 = (gy * height) // grid
        y1 = ((gy + 1) * height) // grid
        for gx in range(grid):
            x0 = (gx * width) // grid
            x1 = ((gx + 1) * width) // grid
            total = 0.0
            n = 0
            for y in range(y0, y1):
                row = y * width
                for x in range(x0, x1):
                    total += pixels[row + x] / 255.0
                    n += 1
            features.append(total / n)
    return features


def load_dataset(root: Path) -> list[tuple[list[float], int, str, Path]]:
    samples = dataset_quality.scan_samples(
        root=root,
        expected_variant="any",
        require_raw_scale=False,
    )
    dataset: list[tuple[list[float], int, str, Path]] = []
    for sample in samples:
        if sample.label not in LABEL_TO_TARGET:
            continue
        dataset.append((gray_features(sample.pixels, sample.width, sample.height), LABEL_TO_TARGET[sample.label], sample.label, sample.path))
    return dataset


def split_dataset(
    dataset: list[tuple[list[float], int, str, Path]],
    train_ratio: float,
    seed: int,
) -> tuple[list[tuple[list[float], int, str, Path]], list[tuple[list[float], int, str, Path]]]:
    rng = random.Random(seed)
    shuffled = list(dataset)
    rng.shuffle(shuffled)
    split = max(1, int(round(len(shuffled) * train_ratio)))
    if split >= len(shuffled) and len(shuffled) > 1:
        split = len(shuffled) - 1
    return shuffled[:split], shuffled[split:]


def train_logreg(
    train_rows: list[tuple[list[float], int, str, Path]],
    epochs: int,
    learning_rate: float,
) -> list[float]:
    if not train_rows:
        raise ValueError("no training samples")
    weights = [0.0] * len(train_rows[0][0])
    for _ in range(epochs):
        for features, target, _label, _path in train_rows:
            pred = sigmoid(sum(weight * feature for weight, feature in zip(weights, features)))
            error = target - pred
            for i, feature in enumerate(features):
                weights[i] += learning_rate * error * feature
    return weights


def predict_confidence(weights: list[float], features: list[float]) -> float:
    return sigmoid(sum(weight * feature for weight, feature in zip(weights, features)))


def evaluate(
    weights: list[float],
    rows: list[tuple[list[float], int, str, Path]],
    threshold: float,
) -> tuple[float, dict[str, int]]:
    confusion = {"tp": 0, "tn": 0, "fp": 0, "fn": 0}
    if not rows:
        return 0.0, confusion
    correct = 0
    for features, target, _label, _path in rows:
        pred = 1 if predict_confidence(weights, features) >= threshold else 0
        if pred == target:
            correct += 1
        if pred == 1 and target == 1:
            confusion["tp"] += 1
        elif pred == 0 and target == 0:
            confusion["tn"] += 1
        elif pred == 1 and target == 0:
            confusion["fp"] += 1
        else:
            confusion["fn"] += 1
    return correct / len(rows), confusion


def write_header(path: Path, weights: list[float], threshold: float) -> None:
    q15 = [int(round(weight * 32768.0)) for weight in weights]
    body = ", ".join(str(value) for value in q15)
    logit_threshold_q15 = int(round(math.log(threshold / (1.0 - threshold)) * 32768.0))
    path.write_text(
        "\n".join(
            [
                "/* Auto-generated by tools/train_gray96_baseline.py. */",
                "#ifndef EDGECARE_MODEL_BASELINE_H",
                "#define EDGECARE_MODEL_BASELINE_H",
                "",
                "#include <stdint.h>",
                "",
                f"#define EDGECARE_BASELINE_FEATURE_COUNT {len(weights)}",
                f"#define EDGECARE_BASELINE_THRESHOLD_Q15 {int(round(threshold * 32768.0))}",
                f"#define EDGECARE_BASELINE_LOGIT_THRESHOLD_Q15 {logit_threshold_q15}",
                f"static const int32_t edgecare_baseline_weights_q15[EDGECARE_BASELINE_FEATURE_COUNT] = {{{body}}};",
                "",
                "#endif /* EDGECARE_MODEL_BASELINE_H */",
                "",
            ]
        ),
        encoding="utf-8",
    )


def train_and_export(
    dataset_root: Path,
    out_dir: Path,
    epochs: int,
    learning_rate: float,
    train_ratio: float,
    seed: int = 7,
    threshold: float = 0.5,
) -> TrainingResult:
    dataset = load_dataset(dataset_root)
    if len(dataset) < 2:
        raise ValueError(f"need at least 2 samples, got {len(dataset)}")
    out_dir.mkdir(parents=True, exist_ok=True)
    train_rows, val_rows = split_dataset(dataset, train_ratio, seed)
    eval_weights = train_logreg(train_rows, epochs, learning_rate)
    val_accuracy, confusion = evaluate(eval_weights, val_rows, threshold)
    export_weights = train_logreg(dataset, epochs, learning_rate)
    metrics = {
        "model": "gray_stats_grid4_logreg_baseline",
        "note": "baseline trained from MCU gray96 samples; validation uses a held-out split, exported weights are retrained on all samples",
        "total_samples": len(dataset),
        "train_samples": len(train_rows),
        "val_samples": len(val_rows),
        "export_samples": len(dataset),
        "val_accuracy": val_accuracy,
        "confusion": confusion,
        "feature_count": len(export_weights),
        "threshold": threshold,
        "export_training": "all_samples",
    }
    (out_dir / "baseline_metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    write_header(out_dir / "edgecare_model_baseline.h", export_weights, threshold)
    return TrainingResult(
        total_samples=len(dataset),
        train_samples=len(train_rows),
        val_samples=len(val_rows),
        export_samples=len(dataset),
        val_accuracy=val_accuracy,
        confusion=confusion,
        export_weights=export_weights,
        out_dir=out_dir,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default="data/raw_gray96")
    parser.add_argument("--out", default="data/models/baseline")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--learning-rate", type=float, default=0.1)
    parser.add_argument("--train-ratio", type=float, default=0.8)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--threshold", type=float, default=0.5)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = train_and_export(
        dataset_root=Path(args.data),
        out_dir=Path(args.out),
        epochs=args.epochs,
        learning_rate=args.learning_rate,
        train_ratio=args.train_ratio,
        seed=args.seed,
        threshold=args.threshold,
    )
    print(f"total_samples={result.total_samples}")
    print(f"train_samples={result.train_samples} val_samples={result.val_samples}")
    print(f"export_samples={result.export_samples}")
    print(f"val_accuracy={result.val_accuracy:.3f}")
    print(f"confusion={result.confusion}")
    print(f"metrics={result.out_dir / 'baseline_metrics.json'}")
    print(f"header={result.out_dir / 'edgecare_model_baseline.h'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
